[workspace]
members = ["cli", "contracts", "contracts/scripts"]

[workspace.package]
edition = "2024_07"

[workspace.dependencies]
cairo_lib = { path = "/home/filip/Work/cairo-lib" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.28.0" }
sncast_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.28.0" }
starknet = "2.7.0"

[workspace.tool.snforge]
exit_first = true

[workspace.tool.fmt]
sort-module-level-items = true
max-line-length = 120

[workspace.scripts]
build_cli = "scarb --profile cli build --package cli"
build_contracts = "scarb build --package contracts"

[profile.cli.cairo]
enable-gas = false
sierra-replace-ids = true

[profile.cli.lib]
casm = true
sierra = true