[workspace]
members = ["cairo", "contracts"]

[workspace.dependencies]
cairo_lib = { git = "https://github.com/HerodotusDev/cairo-lib.git" }
snforge_std = { git = "https://github.com/foundry-rs/starknet-foundry.git", tag = "v0.26.0" }

