[package]
name = "cli"
version = "0.1.0"
author = "Filip Laurentiu"
edition = "2023_11"

# See more keys and their definitions at https://docs.swmansion.com/scarb/docs/reference/manifest.html

[dependencies]
cairo_lib.workspace = true

[dev-dependencies]
snforge_std.workspace = true

[cairo]
enable-gas = false

[lib]
casm = true
sierra = true

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[tool.snforge]
exit_first = true