[package]
name = "starkswirl_contracts"
version = "0.1.0"
author = "Filip Laurentiu"

[dependencies]
starknet = ">=2.6.3"
cairo_lib.workspace = true
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.14.0" }
cairo_verifier = { git = "https://github.com/HerodotusDev/integrity.git" }

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
casm = true
sierra = true
build-external-contracts = ["openzeppelin::token::erc20::erc20::ERC20"]

[tool.fmt]
sort-module-level-items = true
max-line-length = 120

[scripts]
test = "snforge test"

[tool.snforge]
exit_first = true

[[test]]
test-type = "unit"