[package]
name = "contracts"
version = "0.1.0"
author = "Filip Laurentiu"
edition.workspace = true

[dependencies]
starknet.workspace = true
cairo_lib.workspace = true
openzeppelin = { git = "https://github.com/OpenZeppelin/cairo-contracts.git", tag = "v0.15.1" }
cairo_verifier = { git = "https://github.com/HerodotusDev/integrity.git" }
cli = { path = "../cli" }

[dev-dependencies]
snforge_std.workspace = true

[[target.starknet-contract]]
casm = true
sierra = true
build-external-contracts = ["openzeppelin::token::erc20::erc20::ERC20"]

[tool]
snforge.workspace = true
fmt.workspace = true

[scripts]
test = "snforge test"
build_contracts.workspace = true

[[test]]
test-type = "unit"
