[sncast.default]
account = "default"
accounts-file = "~/.starknet_accounts/starknet_open_zeppelin_accounts.json"
url = "http://localhost:9545"

[sncast.dev]
account = "user1"
accounts-file = "devnet/devnet_accounts.json"
url = "http://localhost:5050"
